"""empty message

Revision ID: 0887f2e025aa
Revises: 551d99432fbe
Create Date: 2017-08-27 22:52:37.901000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0887f2e025aa'
down_revision = '551d99432fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###
