"""empty message

Revision ID: 1a05c95e7884
Revises: 90e26111b47f
Create Date: 2017-10-22 15:02:49.825000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a05c95e7884'
down_revision = '90e26111b47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('zan', sa.String(length=100), nullable=True))
    op.alter_column('question', 'label',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'label',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('question', 'zan')
    # ### end Alembic commands ###
