"""empty message

Revision ID: 551d99432fbe
Revises: ccffc9b176a7
Create Date: 2017-08-22 14:45:06.513000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551d99432fbe'
down_revision = 'ccffc9b176a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yx_aiml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_p', sa.Text(), nullable=True),
    sa.Column('content_r', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yx_aiml')
    # ### end Alembic commands ###
