"""empty message

Revision ID: c9ae31cdcc9f
Revises: bfdbfb4f252d
Create Date: 2017-11-01 01:33:21.197000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ae31cdcc9f'
down_revision = 'bfdbfb4f252d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('birthmonth', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('birthplace', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('birthyear', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('contactway', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('hobby', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('institude', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('liveplace', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('motto', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('realname', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('resume', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'resume')
    op.drop_column('user', 'realname')
    op.drop_column('user', 'motto')
    op.drop_column('user', 'liveplace')
    op.drop_column('user', 'institude')
    op.drop_column('user', 'hobby')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'education')
    op.drop_column('user', 'contactway')
    op.drop_column('user', 'birthyear')
    op.drop_column('user', 'birthplace')
    op.drop_column('user', 'birthmonth')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
