"""empty message

Revision ID: e9af6fbfc518
Revises: 0887f2e025aa
Create Date: 2017-10-24 00:20:20.287000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9af6fbfc518'
down_revision = '0887f2e025aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('label', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'label')
    # ### end Alembic commands ###
